const CLIENT_COLLECTION = 'client';
const TRAINER_COLLECTION = 'trainer';
const ADMIN_COLLECTION = 'admin';
const PACKAGE_COLLECTION = 'package';
const PURCHASE_COLLECTION = 'purchase';
const VIDEO_COLLECTION = 'videos';
const CHAT_COLLECTION = 'chat';

module.exports = {
  CLIENT_COLLECTION,
  TRAINER_COLLECTION,
  ADMIN_COLLECTION,
  PACKAGE_COLLECTION,
  VIDEO_COLLECTION,
  PURCHASE_COLLECTION,
  CHAT_COLLECTION,
};
