const CLIENT_COLLECTION = 'client';
const TRAINER_COLLECTION = 'trainer';
const ADMIN_COLLECTION = 'admin';
const PACKAGE_COLLECTION = 'package';

module.exports = {
  CLIENT_COLLECTION,
  TRAINER_COLLECTION,
  ADMIN_COLLECTION,
  PACKAGE_COLLECTION,
};
